### ISSUE TITLE
Support VirusTotal API quota restrictions

### ISSUE THREAD

**Issue by savornicesei** [crazy-max/ghaction-virustotal#96]
Hi all,

From VT documentation, the free accounts are limited to 4 requests/minute.
It would be useful if this GHA would support this rate limit (that could be turned on through a flag) in case there are more than 4 files to be analyzed by VT (e.g. several NuGet packages/dlls).

Thank you.

**Comment by crazy-max** [comment]
Latest release should fix this issue. Set `request_rate: 4` when using the standard free public API.
